# Generated by Django 4.2.4 on 2023-08-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.PositiveIntegerField()),
                ('attack', models.PositiveIntegerField()),
                ('defense', models.PositiveIntegerField()),
                ('speed', models.PositiveIntegerField()),
                ('crit_rate', models.FloatField()),
                ('crit_damage', models.FloatField()),
                ('break_effect', models.FloatField()),
                ('outgoing_healing_boost', models.FloatField()),
                ('max_energy', models.PositiveIntegerField()),
                ('energy_regeneration_rate', models.FloatField()),
                ('effect_hit_rate', models.FloatField()),
                ('effect_resistance', models.FloatField()),
                ('physical_damage_boost', models.FloatField(null=True)),
                ('fire_damage_boost', models.FloatField(null=True)),
                ('ice_damage_boost', models.FloatField(null=True)),
                ('lightning_damage_boost', models.FloatField(null=True)),
                ('wind_damage_boost', models.FloatField(null=True)),
                ('quantum_damage_boost', models.FloatField(null=True)),
                ('imaginary_damage_boost', models.FloatField(null=True)),
                ('physical_resistance_boost', models.FloatField(null=True)),
                ('fire_resistance_boost', models.FloatField(null=True)),
                ('ice_resistance_boost', models.FloatField(null=True)),
                ('lightning_resistance_boost', models.FloatField(null=True)),
                ('wind_resistance_boost', models.FloatField(null=True)),
                ('quantum_resistance_boost', models.FloatField(null=True)),
                ('imaginary_resistance_boost', models.FloatField(null=True)),
            ],
        ),
    ]
