# Generated by Django 4.2.4 on 2023-08-21 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterModels',
            fields=[
                ('name', models.CharField(max_length=75)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('stat_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.characterstats')),
            ],
        ),
    ]
